
export const bodyColorKeywords = ["body color to", 
                                  "body colour to", 
                                  "bady colour to", 
                                  "body to", 
                                  "bodycolor to"];

export const headerColorKeywords = ["header color to",
                                    "header colour to",
                                    "header to", 
                                    "haider color to",
                                    "haider colour to",
                                    "haider to", 
                                    "hyder color to", 
                                    "hyder colour to",
                                    "had colour to",
                                    "had color to",
                                    "hader colour to",
                                    "hader color to",
                                    "Hydra color to",
                                    "Hydra colour to",
                                    "headed color to",
                                    "headed colour to",
                                    "headed to",
                                    ];
export const bodyFontFamilyKeywords = [ "body font family to", "body fontfamily to", "body font to", "font to"]

export const footerColorKeywords = ["footer color to",
                                    "footer colour to",
                                    "photo color to",
                                    "photo colour to",
                                    "photo to",                       
                                    ];
export const persistChangesKeywords = ["persist the changes","persist changes","save changes", "save the changes"]

export const createVariationKeywords = ["create variation","create variations","make variation"]
export const headerFontColorKeywords = ["header font colour to",
                                        "header font color to", 
                                        "haider font color to",
                                        "haider font colour to",
                                        "hyder font color to", 
                                        "hyder font colour to",
                                        "had font colour to",
                                        "had font color to",
                                        "hader font colour to",
                                        "hader font color to",
                                        "Hydra font color to",
                                        "Hydra font fontcolour to",
                                        "headed font color to",
                                        "headed font colour to",
                                        "headed font to",
                                         "header font colour to",
                                        "header font color to", 
                                        "haider font color to",
                                        "haider font colour to",
                                        "hyder font color to", 
                                        "hyder font colour to",
                                        "had font colour to",
                                        "had font color to",
                                        "hader font colour to",
                                        "hader font color to",
                                        "Hydra font color to",
                                        "Hydra font fontcolour to",
                                        "headed font color to",
                                        "headed font colour to",
                                        "headed font to",
                                    
                                        "header text colour to",
                                        "header text color to", 
                                        "haider text color to",
                                        "haider text colour to",
                                        "hyder text color to", 
                                        "hyder text colour to",
                                        "had text colour to",
                                        "had text color to",
                                        "hader text colour to",
                                        "hader text color to",
                                        "Hydra text color to",
                                        "Hydra text fontcolour to",
                                        "headed text color to",
                                        "headed text colour to",
                                        "header text to",
                                        "Hydra text to",
                                        "headed text to"]


                                                            